### ISSUE TITLE
求一份《MMPI-2中文简体字版使用手册》

### ISSUE THREAD

**Issue by RShock** [MMPI-CHN/MMPI-CHN.github.io#1]
想要理解一下背后的原理，看见网页推了这本书，大佬有没有电子书呢？

我的邮箱是418648118@qq.com

感谢！

**Comment by MMPI-CHN** [comment]
你好！
我是去图书馆借阅的纸质书，我手上也没有电子版。
你可以先在学校图书馆找找有没有纸质版或者电子版，超星电子书库里很可能有。

**Comment by RShock** [comment]
好的，我买了实体书

**Comment by MMPI-CHN** [comment]
你好 前两天无意间发现了一份电子资源 在readme里标出来了，如果有需要的话可以看一眼
