### ISSUE TITLE
444题翻译问题；Sc4标准分打表问题

### ISSUE THREAD

**Issue by Crossing-Light** [MMPI-CHN/MMPI-CHN.github.io#12]
444题high-strung不是精力旺盛，而是容易紧张/敏感/神经质。（该题“是”选项归属于量表NEGE神经质和关键条目KB1急性焦虑。）
Sc4女性分数有一段是“65,40,75”，打表错误。

**Comment by MMPI-CHN** [comment]
您好

444题翻译已修 Sc4改成了65 70 75，不一定对，但不会是40这么离谱

之前的邮件还没精力仔细看。

**Comment by Crossing-Light** [comment]
补一个，（或许）Si结语的错别字在“人际关系可能浮浅而不**正**诚”

**Comment by MMPI-CHN** [comment]
应该不是这个吧……
这种东西无所谓了，随缘，哪天看到了再说
